USE [master]
GO

/****** Object:  Database [Lesson6]    Script Date: 27.02.2023 15:06:01 ******/
CREATE DATABASE [Lesson6]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lesson6', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Lesson6.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lesson6_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Lesson6_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lesson6].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lesson6] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lesson6] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lesson6] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lesson6] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lesson6] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lesson6] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lesson6] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lesson6] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lesson6] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lesson6] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lesson6] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lesson6] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lesson6] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lesson6] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lesson6] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lesson6] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lesson6] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lesson6] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lesson6] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lesson6] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lesson6] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lesson6] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lesson6] SET RECOVERY FULL 
GO

ALTER DATABASE [Lesson6] SET  MULTI_USER 
GO

ALTER DATABASE [Lesson6] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lesson6] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lesson6] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lesson6] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lesson6] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lesson6] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Lesson6] SET QUERY_STORE = ON
GO

ALTER DATABASE [Lesson6] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Lesson6] SET  READ_WRITE 
GO